CelebA2LowRes-VAE:
  batch_size: 128
  simul_batch_size: 128
  torch_compile: false
  dataset: "CelebA2LowRes"
  data_dir: "./datasets"
  epochs: 1000
  epochs_per_checkpoint: 100
  lr: 0.0002
  weight_decay: 0.01
  ema_decay: 0.0
  grad_clip: 0.0
  autocast_dtype: "bfloat16"
  lr_scheduler: "cosine"
  val_frac: 0.02
  model: "VAE"
  latent_dim: 128
