CIFAR10-VAE:
  dataset: "CIFAR10"
  mode_type: "VAE"
  batch_size: 512
  n_audits: 1
  n_audit_samples: 20000
  attacks:
    GlobalLossAttack:
      attack: "GlobalLossAttack"
      n_loss_samples: 20
    BASE:
      attack: "BASE"
      prior: 0.5
      n_loss_samples: 20
      calibrated: True
    UncalibratedBASE:
      attack: "BASE"
      prior: 0.5
      n_loss_samples: 20
      calibrated: False
    # XGBAttack:
    #   attack: "ClassifierAttack"
    #   n_loss_samples: 20
    #   classifier: "XGBoost"
    # MLPAttack:
    #   attack: "ClassifierAttack"
    #   n_loss_samples: 20
    #   classifier: "MLP"
