CIFAR10-DDPM:
  batch_size: 128
  simul_batch_size: 512
  dataset: "CIFAR10"
  epochs: 5000
  lr: 0.0002
  val_frac: 0.02
  model: "DDPM"
  base_channels: 128
  channel_mult:
  - 1
  - 2
  - 2
  - 2
  dropout: 0.1
