dataset: CelebA
audit_mode: entity
round_robin: false
mode: exclude_train
min_samples_per_entity: 10
max_samples_per_entity: 10
audit_random_seed: 0
loss_normalization: log_standardized
loss_path_pairs:
- target_loss_paths:
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s0-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s0-comp-sz64-epoch500-n64-nl0p1.pkl
  shadow_loss_paths: &id001
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s1-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s1-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s2-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s2-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s3-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s3-comp-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s4-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s4-comp-sz64-epoch700-n64-nl0p33.pkl
- target_loss_paths:
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s1-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s1-comp-sz64-epoch500-n64-nl0p1.pkl
  shadow_loss_paths: &id002
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s2-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s2-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s3-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s3-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s4-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s4-comp-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s0-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s0-comp-sz64-epoch700-n64-nl0p33.pkl
- target_loss_paths:
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s2-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s2-comp-sz64-epoch500-n64-nl0p1.pkl
  shadow_loss_paths: &id003
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s3-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s3-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s4-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s4-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s0-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s0-comp-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s1-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s1-comp-sz64-epoch700-n64-nl0p33.pkl
- target_loss_paths:
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s3-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s3-comp-sz64-epoch500-n64-nl0p1.pkl
  shadow_loss_paths: &id004
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s4-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s4-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s0-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s0-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s1-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s1-comp-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s2-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s2-comp-sz64-epoch700-n64-nl0p33.pkl
- target_loss_paths:
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s4-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s4-comp-sz64-epoch500-n64-nl0p1.pkl
  shadow_loss_paths: &id005
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s0-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s0-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s1-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500/loss-signals-DDPM-CelebA-ent-f0p5-p0p5-s1-comp-sz64-epoch500-n64-nl0p1.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s2-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s2-comp-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s3-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s3-comp-sz64-epoch700-n64-nl0p33.pkl
- target_loss_paths:
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s0-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s0-comp-sz64-epoch700-n64-nl0p33.pkl
  shadow_loss_paths: *id001
- target_loss_paths:
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s1-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s1-comp-sz64-epoch700-n64-nl0p33.pkl
  shadow_loss_paths: *id002
- target_loss_paths:
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s2-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s2-comp-sz64-epoch700-n64-nl0p33.pkl
  shadow_loss_paths: *id003
- target_loss_paths:
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s3-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s3-comp-sz64-epoch700-n64-nl0p33.pkl
  shadow_loss_paths: *id004
- target_loss_paths:
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s4-sz64-epoch700-n64-nl0p33.pkl
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700/loss-signals-FlowMatching-CelebA-ent-f0p5-p0p5-s4-comp-sz64-epoch700-n64-nl0p33.pkl
  shadow_loss_paths: *id005
attacks:
- name: CompositeLiRA
  attack: CompositeLiRA
  offline: false
  use_full_cov: false
- name: CompositeBASE
  attack: CompositeBASE
  offline: false
  prior: 0.5
results_dir_name: audit_results_entity_mismatched_online
