audit_mode: entity
round_robin: true
audit_random_seed: 0
loss_normalization: log_standardized
audit_groups:
# - dataset: CelebA
#   mode: exclude_train
#   min_samples_per_entity: 5
#   max_samples_per_entity: 15
#   loss_paths:
#   - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500
#   - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700
- dataset: VGGFace2
  mode: hold_out
  min_samples_per_entity: 5
  max_samples_per_entity: 200
  loss_paths:
  - loss-signals/FM-VGGFace2-loss-sigs
results_dir_name: audit_results_entity_core_offline
attacks:
- name: CompositeLiRA
  attack: CompositeLiRA
  loss_transformation: none
  offline: true
  covariance: spherical
  use_global_dispersion: false
- name: CompositeBASE
  attack: CompositeBASE
  offline: true
  prior: 0.5
- name: HBE-GlobalLatent
  attack: HBE_GlobalLatent
  offline: true
  n_folds: 5
  quadrature_nodes: 50
  max_hyper_units: 4096
  factor_steps: 50
  factor_tolerance: 1.0e-7
