dataset: "CelebA"
model_type: "DDPM"
batch_size: 512
n_audit_samples: 30000
audit_mode: "sample"
target_model_paths:
- ""
shadow_model_paths:
- ""
attack:
  attack: "BASE"
  prior: 0.5
  n_loss_samples: 10
