audit_mode: entity
round_robin: true
audit_random_seed: 0
loss_normalization: log_standardized
audit_groups:
- dataset: CelebA
  mode: exclude_train
  min_samples_per_entity: 5
  max_samples_per_entity: 15
  loss_paths:
  - loss-signals/DDPM-CelebA-ent-f0p5-p0p5-sz64-epoch500
  - loss-signals/FM-CelebA-ent-f0p5-p0p5-sz64-epoch700
- dataset: VGGFace2
  mode: hold_out
  min_samples_per_entity: 20
  max_samples_per_entity: 100
  loss_paths:
  - loss-signals/FM-VGGFace2-loss-sigs
results_dir_name: audit_results_entity_core_offline
attacks:
# - name: CompositeLiRA
#   attack: CompositeLiRA
#   offline: true
#   use_full_cov: false
- name: CompositeLiRAv2
  attack: CompositeLiRAv2
  loss_normalization: none
  offline: true
  use_full_cov: false
  use_global_dispersion: false
- name: CompositeBASE
  attack: CompositeBASE
  offline: true
  prior: 0.5
- name: HBE-Simple
  attack: HBE_Simple
  offline: true
  loss_transformation: none
  n_gibbs_samples: 128
  n_gibbs_warmup: 64
  random_seed: 0
- name: HBE-GlobalLatent
  attack: HBE_GlobalLatent
  offline: true
  n_folds: 5
  quadrature_nodes: 24
  max_hyper_units: 4096
  factor_steps: 50
  factor_tolerance: 1.0e-7
