CelebAHQ-DDPM:
  batch_size: 16
  simul_batch_size: 64
  torch_compile: false
  dataset: "CelebAHQ"
  data_dir: "./datasets"
  epochs: 5
  epochs_per_checkpoint: 2
  lr: 0.00002
  val_frac: 0.05
  model: "DDPM"
  base_channels: 128
  channel_mult:
  - 1
  - 1
  - 2
  - 2
  - 4
  - 4
  dropout: 0.0
