dataset: "CelebA2"
data_dir: "./datasets"
res_dir: "./mia/results"
audit_mode: "entity"
mode: "exclude_train"
n_audit_samples_per_entity: 10
min_samples_per_entity: null
max_samples_per_entity: null
score_paths:
  - "DDPM-CelebA2-ent-f0p5-p0p5-sz64-epoch1000/BASE-scores"
