audit_mode: sample
round_robin: true
seed: 0
n_loss_samples: 32
loss_normalization: log_standardized
loss_paths:
- loss-signals/DDPM-CIFAR10-sample
- loss-signals/DDPM-CelebA-sample
- loss-signals/FM-CIFAR10-sample
- loss-signals/FM-CelebA-sample
# - loss-signals/FM-ImageNet32-loss-signals
results_dir_name: audit_results_sample_core_offline_stdtr
n_audit_samples: 100000
attacks:
# - name: BASE
#   attack: BASE
#   offline: true
#   prior: 0.5
# - name: LiRA-global
#   attack: LiRA
#   offline: true
#   loss_transformation: none
#   use_global_dispersion: true
#   share_variance: false
- name: HG_LiRA_r
  attack: HG_LiRA_r
  offline: true
  loss_transformation: none
  n_gibbs_samples: 128
  n_gibbs_warmup: 64
  n_quadrature: 65
